# Generated by Django 4.2.6 on 2023-10-25 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_searchstock_post_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
