# Generated by Django 4.2.6 on 2023-10-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
    ]
